### ISSUE TITLE
View paginated list of posts

### ISSUE THREAD

**Issue by dmuresanu** [dmuresanu/La-Salsa-del-Diablo#1]
As a **role** I can **capability** so that **received benefit**

## Acceptance Criteria
 - Acceptance 1
 - Acceptance 2
 - Acceptance 2
## Tasks
   - [ ] Sample Task 1 (create backend)
   - [ ] Sample Task 2 ( create functionality with HTML and CSS)
     - [ ] Sample Nested Task (Style to suit web theme)
